server:
  port: ${REVIEW_SERVICE_PORT}

spring:
  application:
    name: review-service
  datasource:
    url: ${CODECTION_DATABASE_URL}
    username: ${CODECTION_DATABASE_USERNAME}
    password: ${CODECTION_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

git:
  baseUrl: ${GIT_BASEURL}