server:
  port: ${REVIEW_SERVICE_PORT}

spring:
  application:
    name: review-service
  datasource:
    url: ${CODECTION_DATABASE_URL}
    username: ${CODECTION_DATABASE_USERNAME}
    password: ${CODECTION_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: postgresql

max-pin: 3

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_URL}

git:
  baseUrl: ${GIT_BASEURL}

springdoc:
  api-docs:
    path: /api-doc
    groups:
      enabled: true
  cache:
    disabled: true
  model-and-view-allowed: true